video_analytics/about/urls.py
from django.urls import path
from about import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

video_analytics/video/urls.py
from django.urls import path

from video import views

app_name = 'video'


urlpatterns = [
    # Для открытия видео отдельно
    path('stream/<int:pk>/', views.get_streaming_video, name='stream'),
    path('video/<int:pk>/', views.get_video, name='video'),
    path('video/create/', views.create_video, name='create_video'),
    path('new/', views.new_index, name='new_index'),
    path('done/', views.done_index, name='done_index'),
    path('', views.index, name='index'),
]

video_analytics/video_analytics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('video.urls', namespace='videos')),
    path('', include('check_list.urls', namespace='check_list')),
]

handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

# Эти строки — в самый конец файла:
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

video_analytics/video/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import FileExtensionValidator, RegexValidator

User = get_user_model()

GREEN = '#008000'
ORANGE = '#FF9900'
RED = '#FF0000'

CHOICE_STATUS = (
    (GREEN, 'зеленый'),
    (ORANGE, 'оранжевый'),
    (RED, 'красный'),
)

GROUPS_CHOISE = {}


class Status(models.Model):
    """Модель статусов видео с выбором цвета."""
    name = models.CharField(
        verbose_name='Статус',
        help_text='Статус просмотра видео',
        max_length=50,
        unique=True,
    )
    color = models.CharField(
        verbose_name='Цвет статуса',
        help_text='Цвет в формате HEX',
        max_length=7,
        validators=(
            RegexValidator(
                regex=r'#[A-F\d]{6}',
                message='Цвет толжен быть в формате HEX!'
            ),
        ),
        choices=CHOICE_STATUS,
        unique=True,
    )
    slug = models.SlugField(
        verbose_name='Слаг статуса',
        help_text='уникальный слаг статуса до 100 символов',
        max_length=100,
        unique=True,
    )

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self) -> str:
        return self.name


class Group(models.Model):
    """Модель для описания групп."""
    name = models.CharField(
        max_length=50,
        verbose_name='Название группы',
        help_text='название группы видео',
    )
    slug = models.SlugField(
        verbose_name='Уникальный slug',
        help_text='slug группы',
        max_length=20,
        unique=True,
    )
    description = models.TextField(
        max_length=200,
        verbose_name='Описание',
        help_text='Описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.name


class Video(models.Model):
    """Модель видеозаписей."""
    name = models.CharField(
        max_length=50,
        null=False,
        verbose_name='название',
        help_text='название видео',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='videos',
        verbose_name='автор видео',
        help_text='Сотрудник загрузивший видео',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата публикации в формате "ДД название месяца ГГГГ"',
    )
    description = models.CharField(
        max_length=200,
        verbose_name='описание',
        help_text='описание видео',
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE,
        related_name='videos',
        verbose_name='статус',
        help_text='статус видео'
    )
    video = models.FileField(
        upload_to='video/',
        blank=False,
        unique=True,
        validators=(
            FileExtensionValidator(
                allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'),
                code='неверное расширение',
            ),
        ),
        verbose_name='Видеозапись',
        help_text='видеофайл',
    )
    image = models.ImageField(
        upload_to='video/',
        blank=True,
        verbose_name='Картинка',
        help_text='Изображение поста',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.DO_NOTHING,
        verbose_name='группа',
        help_text='группа видео',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Видеозапись'
        verbose_name_plural = 'Видеозаписи'

    def __str__(self) -> str:
        return self.name

video_analytics/video/forms.py
from django import forms
from video.models import Video


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = '__all__'

video_analytics/video/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from django.http import StreamingHttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from video.services import open_file
from video.models import Video
from video.forms import VideoForm
from check_list.models import PersonnelActionsValue
from check_list.forms import CheckListForm
from video_analytics.settings import VIDEO_PER_PAGE
from django.shortcuts import render, get_object_or_404
from check_list.forms import CheckListForm
import logging
from django.shortcuts import get_object_or_404
from check_list.models import PersonnelActions

logging.basicConfig(
    level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s'
)


def index(request):
    post_list = Video.objects.all()
    paginator = Paginator(post_list, VIDEO_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'video/index.html', context)


def new_index(request):
    post_list = Video.objects.filter(status__name='Новое')
    paginator = Paginator(post_list, VIDEO_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    for video in page_obj.object_list:
        video.status_name = video.status.name
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'video/new_index.html', context)


def done_index(request):
    post_list = Video.objects.filter(status__name='Просмотрено')
    logging.info(f'{post_list}')
    paginator = Paginator(post_list, VIDEO_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    for video in page_obj.object_list:
        video.status_name = video.status.name
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'video/done_index.html', context)


def get_list_video(request):
    return render(
        request, 'video/index.html', {'video_list': Video.objects.all()}
    )


@login_required
def create_video(request):
    form = VideoForm(request.POST, request.FILES or None)
    if request.method != 'POST':
        form = VideoForm()
    if form.is_valid():
        video = form.save(commit=False)
        video.save()
        return index(request)
    return render(request, 'video/create_video.html', {'form': form})


def get_streaming_video(request, pk: int):
    file, status_code, content_length, content_range = open_file(request, pk)
    response = StreamingHttpResponse(
        file, status=status_code, content_type='video/mp4'
    )

    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Cache-Control'] = 'no-cache'
    response['Content-Range'] = content_range
    return response


def get_video(request, pk):
    video = get_object_or_404(Video, pk=pk)
    video.checklist = video.check_lists.all()
    for checklists in video.checklist:
        checklists.actions = checklists.personnelactionsvalue_set.all()
    if request.method == 'POST':
        form = CheckListForm(request.POST)
        form.video = video
        if form.is_valid():
            check_list_instance = form.save(commit=False)
            check_list_instance.save()

            formset = form.formset
            for i, formset_form in enumerate(formset.forms):
                value = request.POST.get(
                    f'personnelactionsvalue_set-{i}-value'
                )
                logging.info(f'{value}')
                logging.info(f'{value}')

                description = request.POST.get(
                    f'personnelactionsvalue_set-{i}-description'
                )
                logging.info(f'{description}')

                personnel_action_id = request.POST.get(
                    f'personnelactionsvalue_set-{i}-personnel_action'
                )
                logging.info(f'{personnel_action_id}')

                personnel_action_instance = get_object_or_404(
                    PersonnelActions,
                    id=personnel_action_id
                )

                PersonnelActionsValue.objects.create(
                    value=value,
                    description=description,
                    check_list_id=check_list_instance,
                    personnel_action=personnel_action_instance,
                )

        return index(request)
    else:
        form = CheckListForm(initial={'video': video})

    return render(request, 'video/video.html', {'form': form, 'video': video})

video_analytics/templates/video/video copy.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="main-posts">
          <h3>
            {{ video.name }}
            <small class="text-muted">{{ video.description }}  <span class="date">{{ video.pub_date }}</span></small>
          </h3>
        </div> 
      </div> 
    </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="video-section">
          <video
              id="my-video"
              class="video-js"
              controls
              preload="auto"
              width="100%"
              height="auto"
              data-setup="{}"
          >
            <source src="{% url 'video:stream' video.id %}" type="video/mp4"/>
            <source src="{% url 'video:stream' video.id %}" type="video/webm"/>
            <source src="{% url 'video:stream' video.id %}" type="video/MOV"/>
          </video>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        {% if form.errors %}
          {% for field in form %}
            {% if field.errors %}
              <div class="alert alert-danger">
                {{ field.label|escape }}:
                {% for error in field.errors %}
                  {{ error|escape }}
                {% endfor %}
              </div>
            {% endif %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}

        {% if video.checklist %}

        {% for check in video.checklist %}
        <div class="form-group row my-3 p-3">
        <p><h3><small class="text-muted">Чек-лист:</small> {{check.name }}</h3></p>
        <p><small class="text-muted">Подразделение:</small> {{check.structural_subdivision }}</p>
        <p><small class="text-muted">Проверяющий:</small> {{check.inspector }}</p>
        {% comment %} {% for actions in check.actions%} {% endcomment %}
        <table class="table table-sm">
          <p><small class="text-muted">Замечания из чек-листа:</small></p>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Описание замечания</th>
              <th scope="col">Оценка</th>
              <th scope="col">Описание</th>
            </tr>
          </thead>
          
          <tbody>
            {% for actions in check.actions%}
              <tr>
                <td scope="row">{{ actions.id }}</td>
                <td scope="row">{{actions.personnel_action }}</td>
                <td scope="row">{{actions.value }}</td>
                <td scope="row">{{ check_list.video }}</td>
                <td scope="row">{{actions.description }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% comment %} {% endfor %} {% endcomment %}
        </div>
        {% endfor %}

        {% else %}

        <form method="post" enctype="multipart/form-data" action="{% url 'video:video' pk=video.id %}">
          {% csrf_token %}

          <div class="form-group row my-3 p-3">
            <h3>Чек-лист:</h3>
           <label for="form.text.label">{{ form.video.label }}
              <span class="required text-danger">*</span>                  
            </label>
            {{ form.video }}
            <input type="hidden" name="{{ form.video.name }}" value="{{ form.video.value }}">
            <small id="id_text-help" class="form-text text-muted">
              заполняется автоматически
            </small>
          </div>

          <script>
            document.getElementById("id_video").disabled = true;
          </script> 


          <div class="form-group row my-3 p-3">
            <label for="form.text.label">{{ form.record_date.label }}
              <span class="required text-danger">*</span>                  
            </label>
            {{ form.record_date }}
            <small id="id_text-help" class="form-text text-muted">
              {{ form.name.record_date }}
            </small>
          </div>


          <div class="form-group row my-3 p-3">
            <label for="form.text.label">{{ form.name.label }}
              <span class="required text-danger">*</span>                  
            </label>
            {{ form.name }}
            <small id="id_text-help" class="form-text text-muted">
              {{ form.name.help_text }}
            </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="form.text.label"> Структурное подразделение
              <span class="required text-danger">*</span>                  
            </label>

            <div class="form-image row my-3 p-3">
              <label for="form.image.label" class="form-label">{{ form.structural_subdivision.label }}</label>
              <label>
                {{ form.structural_subdivision }}
              </label>
              <small id="id_text-help" class="form-text text-muted">
                {{ form.structural_subdivision.help_text }}
              </small>                    
            </div>


          </div>
          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.working_place.label }}
              <span class="required text-danger">*</span>  
            </label>
            <label>
              {{ form.working_place }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.working_place.help_text }}
            </small>                  
          </div>
          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.bp_number.label }}</label>
            <label>
              {{ form.bp_number }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.bp_number.help_text }}
            </small>                  
          </div>

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.working_person.label }}</label>
            <label>
              {{ form.working_person }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.working_person.help_text }}
            </small>                    
          </div>

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.controlling_person.label }}</label>
            <label>
              {{ form.controlling_person }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.controlling_person.help_text }}
            </small>                    
          </div>

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.recording_quality.label }}</label>
            <label>
              {{ form.recording_quality }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.recording_quality.help_text }}
            </small>                    
          </div>

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.inspector.label }}</label>
            <label>
              {{ form.inspector }}
            </label>
            <small id="id_text-help" class="form-text text-muted">
              {{ form.inspector.help_text }}
            </small>                    
          </div>



          <div class="form-image row my-3 p-3">
            <label for="id_personnel_actions_values-0-personnel_action">Действия персонала:</label>

            {{ formset.management_form }}

            {% for formset_form in form.formset %}
              
                <select class="form-select row my-3 p-3" style="white-space: normal;" aria-label="Disabled select example" disabled>
                    <option selected>Описание</option>
                    <option{{ formset_form.personnel_action }}</option>
                </select>

                <div class="col-md-2">
                  {% comment %} {{ formset_form.value.errors }} {% endcomment %}
                  {{ formset_form.value.label_tag }}
                  {{ formset_form.value }}

              </div>
              <div class="col-md-2">
                  {% comment %} {{ formset_form.description.errors }} {% endcomment %}
                  {{ formset_form.description.label_tag }}
                  {{ formset_form.description }}


                </div> 
            
                  <input type="hidden" name="{{ formset_form.prefix }}-check_list_id" value="{{ formset_form.check_list_id.value }}">
                  <input type="hidden" name="{{ formset_form.prefix }}-personnel_action" value="{{ formset_form.personnel_action.value }}">
              
            {% endfor %}

        </div>
        

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.brif_conclusion.label }}</label>
              {{ form.brif_conclusion }}
            <small id="id_text-help" class="form-text text-muted">
              {{ form.brif_conclusion.help_text }}
            </small>                    
          </div>

          <div class="form-image row my-3 p-3">
            <label for="form.image.label" class="form-label">{{ form.offer.label }}</label>
              {{ form.offer }}
            <small id="id_text-help" class="form-text text-muted">
              {{ form.offer.help_text }}
            </small>                    
          
            <div class="form-image row my-3 p-3">
            </div>
          <button type="submit" class="btn btn-primary">
            
            {% if is_edit %}
              Сохранить
            {% else %} 
              Сохранить чек-лист
            {% endif %} 
          </button>
          {% endif %}
        </div>
        <div class="d-flex justify-content-end"></div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

video_analytics/templates/video/video.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 d-flex">
        <!-- Видео слева -->
        <div class="video-section" style="flex: 0 0 40%; max-width: 40%;">
          <video
              id="my-video"
              class="video-js"
              controls
              preload="auto"
              width="100%"
              height="auto"
              data-setup="{}"
          >
            <source src="{% url 'video:stream' video.id %}" type="video/mp4"/>
            <source src="{% url 'video:stream' video.id %}" type="video/webm"/>
            <source src="{% url 'video:stream' video.id %}" type="video/MOV"/>
          </video>
          <div class="main-posts">
            <h3>
              {{ video.name }}
              <small class="text-muted">{{ video.description }}  <span class="date">{{ video.pub_date }}</span></small>
            </h3>
          </div>
        </div>

        <!-- Текст справа -->
        <div class="text-section" style="flex: 1; overflow-y: auto; max-height: 80vh; padding-left: 20px;">
          

          {% if form.errors %}
            {% for field in form %}
              {% if field.errors %}
                <div class="alert alert-danger">
                  {{ field.label|escape }}:
                  {% for error in field.errors %}
                    {{ error|escape }}
                  {% endfor %}
                </div>
              {% endif %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          {% if video.checklist %}
            {% for check in video.checklist %}
              <div class="form-group row my-3 p-3">
                <p><h3><small class="text-muted">Чек-лист:</small> {{check.name }}</h3></p>
                <p><small class="text-muted">Подразделение:</small> {{check.structural_subdivision }}</p>
                <p><small class="text-muted">Проверяющий:</small> {{check.inspector }}</p>
                <table class="table table-sm">
                  <p><small class="text-muted">Замечания из чек-листа:</small></p>
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Описание замечания</th>
                      <th scope="col">Оценка</th>
                      <th scope="col">Описание</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for actions in check.actions %}
                      <tr>
                        <td scope="row">{{ actions.id }}</td>
                        <td scope="row">{{ actions.personnel_action }}</td>
                        <td scope="row">{{ actions.value }}</td>
                        <td scope="row">{{ actions.description }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            {% endfor %}
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'video:video' pk=video.id %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <h3>Чек-лист:</h3>
               <label for="form.text.label">{{ form.video.label }}
                  <span class="required text-danger">*</span>                  
                </label>
                {{ form.video }}
                <input type="hidden" name="{{ form.video.name }}" value="{{ form.video.value }}">
                <small id="id_text-help" class="form-text text-muted">
                  заполняется автоматически
                </small>
              </div>
    
              <script>
                document.getElementById("id_video").disabled = true;
              </script> 
    
    
              <div class="form-group row my-3 p-3">
                <label for="form.text.label">{{ form.record_date.label }}
                  <span class="required text-danger">*</span>                  
                </label>
                {{ form.record_date }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.name.record_date }}
                </small>
              </div>
    
    
              <div class="form-group row my-3 p-3">
                <label for="form.text.label">{{ form.name.label }}
                  <span class="required text-danger">*</span>                  
                </label>
                {{ form.name }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.name.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="form.text.label"> Структурное подразделение
                  <span class="required text-danger">*</span>                  
                </label>
    
                <div class="form-image row my-3 p-3">
                  <label for="form.image.label" class="form-label">{{ form.structural_subdivision.label }}</label>
                  <label>
                    {{ form.structural_subdivision }}
                  </label>
                  <small id="id_text-help" class="form-text text-muted">
                    {{ form.structural_subdivision.help_text }}
                  </small>                    
                </div>
    
    
              </div>
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.working_place.label }}
                  <span class="required text-danger">*</span>  
                </label>
                <label>
                  {{ form.working_place }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.working_place.help_text }}
                </small>                  
              </div>
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.bp_number.label }}</label>
                <label>
                  {{ form.bp_number }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.bp_number.help_text }}
                </small>                  
              </div>
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.working_person.label }}</label>
                <label>
                  {{ form.working_person }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.working_person.help_text }}
                </small>                    
              </div>
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.controlling_person.label }}</label>
                <label>
                  {{ form.controlling_person }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.controlling_person.help_text }}
                </small>                    
              </div>
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.recording_quality.label }}</label>
                <label>
                  {{ form.recording_quality }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.recording_quality.help_text }}
                </small>                    
              </div>
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.inspector.label }}</label>
                <label>
                  {{ form.inspector }}
                </label>
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.inspector.help_text }}
                </small>                    
              </div>
    
    
    
              <div class="form-image row my-3 p-3">
                <label for="id_personnel_actions_values-0-personnel_action">Действия персонала:</label>
    
                {{ formset.management_form }}
    
                {% for formset_form in form.formset %}
                  
                    <select class="form-select row my-3 p-3" style="white-space: normal;" aria-label="Disabled select example" disabled>
                        <option selected>Описание</option>
                        <option{{ formset_form.personnel_action }}</option>
                    </select>
    
                    <div class="col-md-2">
                      {% comment %} {{ formset_form.value.errors }} {% endcomment %}
                      {{ formset_form.value.label_tag }}
                      {{ formset_form.value }}
    
                  </div>
                  <div class="col-md-2">
                      {% comment %} {{ formset_form.description.errors }} {% endcomment %}
                      {{ formset_form.description.label_tag }}
                      {{ formset_form.description }}
    
    
                    </div> 
                
                      <input type="hidden" name="{{ formset_form.prefix }}-check_list_id" value="{{ formset_form.check_list_id.value }}">
                      <input type="hidden" name="{{ formset_form.prefix }}-personnel_action" value="{{ formset_form.personnel_action.value }}">
                  
                {% endfor %}
    
            </div>
            
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.brif_conclusion.label }}</label>
                  {{ form.brif_conclusion }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.brif_conclusion.help_text }}
                </small>                    
              </div>
    
              <div class="form-image row my-3 p-3">
                <label for="form.image.label" class="form-label">{{ form.offer.label }}</label>
                  {{ form.offer }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.offer.help_text }}
                </small>                    
              
                <div class="form-image row my-3 p-3">
                </div>
              <button type="submit" class="btn btn-primary">
                
                {% if is_edit %}
                  Сохранить
                {% else %} 
                  Сохранить чек-лист
              </button>
              {% endif %}
            </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}